---
dnf_packages_dev:
  # java
  - java-21-openjdk-devel
  - java-21-openjdk-javadoc
  - java-21-openjdk-src
  - java-21-openjdk-jmods
  - maven

  # javascript
  - nodejs
  - nodejs-npm
  - pnpm

  # python
  - uv

flatpak_packages_dev:
  - com.getpostman.Postman
  - com.mongodb.Compass
  - org.pgadmin.pgadmin4
