---
flatpak_packages_media:
  # video
  - com.obsproject.Studio
  # - org.nickvision.tubeconverter
  - org.shotcut.Shotcut
  - org.videolan.VLC

  # audio
  - com.spotify.Client
  - org.atheme.audacious
  # - org.audacityteam.Audacity
  - org.gnome.SoundRecorder
  - org.nickvision.tagger

  # image
  - be.alexandervanhee.gradia
  - com.github.PintaProject.Pinta
  - com.jgraph.drawio.desktop
  - io.gitlab.adhami3310.Converter
  - org.gnome.design.Emblem
  - org.gnome.design.IconLibrary
  # - org.kde.gwenview
