---
dnf_packages_tools:
  # customization
  - dconf-editor
  - gnome-extensions-app
  - gnome-tweaks

  # utilities
  - ddcutil
  - fastfetch
  - file-roller
  - ftp
  - gh
  - glances
  - intel-gmmlib
  - jq
  - nmap
  - openssl
  - qt
  - shfmt
  - sysprof
  - unrar
  - vim-enhanced

  # pdf organization
  - pdftk-java

  # misc
  - qbittorrent

flatpak_packages_tools:
  # customization
  - com.github.tchx84.Flatseal

  # utilities
  - io.gitlab.liferooter.TextPieces
  - io.podman_desktop.PodmanDesktop
  # - org.gnome.Boxes
  - org.gnome.dspy
  - org.remmina.Remmina
  - org.gnome.Papers

  # misc
  - org.telegram.desktop
