#:schema https://developers.openai.com/codex/config-schema.json

################################################################################
# core
################################################################################
model = "gpt-5.3-codex"
model_provider = "openai"


################################################################################
# reasoning
################################################################################
model_reasoning_effort = "medium"
model_reasoning_summary = "auto"
model_verbosity = "medium"


################################################################################
# approval
################################################################################
approval_policy = "on-request"
sandbox_mode = "workspace-write"


################################################################################
# updates
################################################################################
check_for_update_on_startup = false


################################################################################
# web search
################################################################################
web_search = "cached"


################################################################################
# features
################################################################################
[features]
shell_tool = true
unified_exec = true
shell_snapshot = true


################################################################################
# trust level
################################################################################
[projects]
[projects."/home/zbhavyai/Github"]
trust_level = "trusted"

[projects."/home/zbhavyai/Bitbucket"]
trust_level = "trusted"


################################################################################
# ui
################################################################################
[tui]
notifications = false
animations = true
show_tooltips = true


################################################################################
# history
################################################################################
[history]
persistence = "save-all"
max_bytes = 104857600


################################################################################
# feedback
################################################################################
[feedback]
enabled = false
