---
vscode_extensions:
  DEFAULT:
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - github.copilot
    - github.copilot-chat
    - mkhl.shfmt
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.remote-explorer
    - pkief.material-icon-theme
    - redhat.vscode-xml
    - redhat.vscode-yaml
  JAVA:
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - github.copilot
    - github.copilot-chat
    - josevseb.google-java-format-for-vs-code
    - mkhl.shfmt
    - ms-azuretools.vscode-containers
    - pkief.material-icon-theme
    - redhat.java
    - redhat.vscode-microprofile
    - redhat.vscode-quarkus
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - renesaarsoo.sql-formatter-vsc
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
  JAVASCRIPT:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - github.copilot
    - github.copilot-chat
    - mkhl.shfmt
    - ms-azuretools.vscode-containers
    - pkief.material-icon-theme
    - redhat.vscode-xml
    - redhat.vscode-yaml
  PYTHON:
    - charliermarsh.ruff
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - github.copilot
    - github.copilot-chat
    - mkhl.shfmt
    - ms-azuretools.vscode-containers
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.vscode-python-envs
    - pkief.material-icon-theme
    - redhat.ansible
    - redhat.vscode-xml
    - redhat.vscode-yaml
