---
- name: Ensure wallpaper directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/Pictures/Wallpapers"
    state: directory
    mode: "0755"

- name: Update background directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/share/backgrounds"
    state: link
    src: "{{ ansible_facts['env']['HOME'] }}/Pictures/Wallpapers"
  changed_when: true
